CREATE TABLE "restaurant_settings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"restaurant_name" text NOT NULL,
	"restaurant_description" text,
	"restaurant_phone" text,
	"restaurant_email" text,
	"restaurant_address" text,
	"is_ordering_enabled" boolean DEFAULT true NOT NULL,
	"minimum_order_amount" numeric(10, 2) DEFAULT '15.00' NOT NULL,
	"delivery_fee" numeric(10, 2) DEFAULT '5.99' NOT NULL,
	"preparation_time" integer DEFAULT 30 NOT NULL,
	"email_notifications" boolean DEFAULT true NOT NULL,
	"sms_notifications" boolean DEFAULT false NOT NULL,
	"push_notifications" boolean DEFAULT true NOT NULL,
	"maintenance_mode" boolean DEFAULT false NOT NULL,
	"auto_backup" boolean DEFAULT true NOT NULL,
	"timezone" text DEFAULT 'America/New_York' NOT NULL,
	"currency" text DEFAULT 'USD' NOT NULL,
	"accept_cash_on_delivery" boolean DEFAULT true NOT NULL,
	"auto_accept_orders" boolean DEFAULT false NOT NULL,
	"loyalty_points_rate" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
