CREATE TABLE upi_payment (
  id SERIAL PRIMARY KEY,
  order_id VARCHAR(255) NOT NULL,
  upi_id VARCHAR(255) NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  status VARCHAR(50) NOT NULL,
  transaction_id VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
